# Turn vector csv into npy

In [1]:
# Basic import
import os
import sys
import json
import shutil
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Helper function
def writeProgress(msg, count, total):
    sys.stdout.write(msg + "{:.2%}\r".format(count/total))
    sys.stdout.flush()
    
def newPath(path):
    if not os.path.isdir(path):
        os.mkdir(path)

def read_json(src_path):
    with open(src_path, 'r') as json_file:
        data = json.load(json_file)
    return data

def write_json(data,dst_path):
    with open(dst_path, 'w') as outfile:
        json.dump(data, outfile)

def writeLog(row):
    with open('log.txt', 'a') as outfile:
        outfile.write(row + '\n')

def getErrMsg(e):
    error_class = e.__class__.__name__ #取得錯誤類型
    detail = e.args[0] #取得詳細內容
    errMsg = "[{}] {}".format(error_class, detail)
    return errMsg

# Feature

## Text

In [3]:
PATH = '../Text/output/TextFeatureVec.csv'
SAVE_NAME = 'text'

In [4]:
df = pd.read_csv(PATH, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,300
0,21bridgesmovie,0.394357,0.235372,0.854403,0.342696,0.0,1.500048,0.0,0.403149,0.625406,...,2.410984,0.399076,2.394528,0.0,1.630364,3.524209,3.571405,3.402126,0.503089,2.791061
1,47metersdown,1.446867,1.456720,1.087456,1.219514,0.0,0.756495,0.0,0.840129,0.767282,...,0.743066,1.343877,1.067933,0.0,0.533282,0.655600,1.858642,0.784104,0.577789,1.184285
2,abeautifuldaymovie,0.802951,0.120639,1.965423,0.492501,0.0,0.811695,0.0,0.408202,1.528954,...,0.327671,0.245046,2.416978,0.0,1.346555,0.666192,2.788293,0.498391,1.278117,2.303997
3,abominablemovie,0.925836,0.184008,0.446210,0.308441,0.0,0.519721,0.0,0.809948,0.447716,...,0.354478,0.000000,0.681129,0.0,0.340756,0.284469,0.275000,0.590535,0.405641,0.337373
4,adastramovie,1.934018,1.310400,0.668950,1.532149,0.0,1.249086,0.0,0.350703,0.498935,...,2.174542,1.198994,1.956161,0.0,1.630883,3.077870,3.096041,3.131805,0.500006,2.409130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,wrinklestheclown,0.947369,0.731974,1.283203,0.752349,0.0,1.103076,0.0,1.482063,0.916391,...,0.110939,0.807778,0.692659,0.0,0.217799,0.314982,0.224754,0.149137,0.709096,0.211519
162,xmenmovies,1.191364,0.526732,2.551586,0.733940,0.0,1.337926,0.0,0.584880,1.571372,...,3.980859,0.426892,1.651679,0.0,1.070698,4.263134,0.971207,5.024591,1.665927,0.924991
163,yardiefilm,1.420822,0.665608,2.777351,0.783862,0.0,1.894592,0.0,0.887966,1.674957,...,1.279723,0.456108,2.555660,0.0,1.112406,2.487240,4.089377,2.189274,1.832878,3.282995
164,yesterdaymovie,2.737671,1.565903,1.276306,2.199891,0.0,0.724438,0.0,1.502795,1.081938,...,0.289262,1.410571,1.042772,0.0,0.639581,0.326993,1.213286,0.489222,0.864493,0.916699
165,zombieland,0.950335,0.662254,1.185297,0.508620,0.0,1.100105,0.0,1.684852,0.934083,...,2.963037,0.676770,1.394752,0.0,0.348194,3.298094,0.415648,3.698897,0.876782,0.621250

In [5]:
df = df.loc[:, 1:]
df

,1,2,3,4,5,6,7,8,9,10,...,291,292,293,294,295,296,297,298,299,300
0,0.394357,0.235372,0.854403,0.342696,0.0,1.500048,0.0,0.403149,0.625406,1.448432,...,2.410984,0.399076,2.394528,0.0,1.630364,3.524209,3.571405,3.402126,0.503089,2.791061
1,1.446867,1.456720,1.087456,1.219514,0.0,0.756495,0.0,0.840129,0.767282,0.896483,...,0.743066,1.343877,1.067933,0.0,0.533282,0.655600,1.858642,0.784104,0.577789,1.184285
2,0.802951,0.120639,1.965423,0.492501,0.0,0.811695,0.0,0.408202,1.528954,2.635449,...,0.327671,0.245046,2.416978,0.0,1.346555,0.666192,2.788293,0.498391,1.278117,2.303997
3,0.925836,0.184008,0.446210,0.308441,0.0,0.519721,0.0,0.809948,0.447716,0.672917,...,0.354478,0.000000,0.681129,0.0,0.340756,0.284469,0.275000,0.590535,0.405641,0.337373
4,1.934018,1.310400,0.668950,1.532149,0.0,1.249086,0.0,0.350703,0.498935,1.341668,...,2.174542,1.198994,1.956161,0.0,1.630883,3.077870,3.096041,3.131805,0.500006,2.409130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0.947369,0.731974,1.283203,0.752349,0.0,1.103076,0.0,1.482063,0.916391,0.970854,...,0.110939,0.807778,0.692659,0.0,0.217799,0.314982,0.224754,0.149137,0.709096,0.211519
162,1.191364,0.526732,2.551586,0.733940,0.0,1.337926,0.0,0.584880,1.571372,1.810064,...,3.980859,0.426892,1.651679,0.0,1.070698,4.263134,0.971207,5.024591,1.665927,0.924991
163,1.420822,0.665608,2.777351,0.783862,0.0,1.894592,0.0,0.887966,1.674957,1.882940,...,1.279723,0.456108,2.555660,0.0,1.112406,2.487240,4.089377,2.189274,1.832878,3.282995
164,2.737671,1.565903,1.276306,2.199891,0.0,0.724438,0.0,1.502795,1.081938,1.325111,...,0.289262,1.410571,1.042772,0.0,0.639581,0.326993,1.213286,0.489222,0.864493,0.916699
165,0.950335,0.662254,1.185297,0.508620,0.0,1.100105,0.0,1.684852,0.934083,1.301710,...,2.963037,0.676770,1.394752,0.0,0.348194,3.298094,0.415648,3.698897,0.876782,0.621250

In [6]:
npy = df.to_numpy()
print(npy.shape, npy)

(166, 300) [[0.3943566  0.23537198 0.854403   ... 3.4021258  0.50308883 2.7910614 ]
 [1.4468665  1.45672    1.0874561  ... 0.78410447 0.5777885  1.1842852 ]
 [0.8029508  0.12063935 1.9654235  ... 0.49839103 1.2781174  2.3039973 ]
 ...
 [1.4208224  0.6656082  2.7773507  ... 2.1892736  1.8328775  3.2829945 ]
 [2.7376714  1.5659028  1.2763064  ... 0.48922157 0.864493   0.9166994 ]
 [0.950335   0.66225404 1.1852973  ... 3.6988966  0.876782   0.62125033]]

In [7]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Image

### Poster

In [8]:
PATH = '../Image/Sample/output/PosterFeatureVec.csv'
SAVE_NAME = 'poster'

In [9]:
df = pd.read_csv(PATH, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,21bridgesmovie.jpg,3.387048,0.0,0.0,4.010987,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.836308
1,47metersdown.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,4.681221,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.379242
2,abeautifuldaymovie.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.466343
3,abominablemovie.jpg,6.915580,0.0,0.0,0.000000,0.0,0.0,0.0,9.828920,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.211412
4,adastramovie.jpg,0.028479,0.0,0.0,1.667131,0.0,0.0,0.0,2.236325,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.415615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,wrinklestheclown.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.045490,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.886146
162,xmenmovies.jpg,18.459608,0.0,0.0,8.158738,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.567715
163,yardiefilm.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.618315,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.543765
164,yesterdaymovie.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,4.909546,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.108469
165,zombieland.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.001880

In [10]:
df = df.loc[:, 1:]
df

,1,2,3,4,5,6,7,8,9,10,...,247,248,249,250,251,252,253,254,255,256
0,3.387048,0.0,0.0,4.010987,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.836308
1,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,4.681221,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.379242
2,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.466343
3,6.915580,0.0,0.0,0.000000,0.0,0.0,0.0,9.828920,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.211412
4,0.028479,0.0,0.0,1.667131,0.0,0.0,0.0,2.236325,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.415615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.045490,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.886146
162,18.459608,0.0,0.0,8.158738,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.567715
163,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.618315,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.543765
164,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,4.909546,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.108469
165,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.001880

In [11]:
npy = df.to_numpy()
print(npy.shape, npy)

(166, 256) [[ 3.3870482  0.         0.        ...  0.         0.        12.836308 ]
 [ 0.         0.         0.        ...  0.         0.        14.379242 ]
 [ 0.         0.         0.        ...  0.         0.        16.466343 ]
 ...
 [ 0.         0.         0.        ...  0.         0.         9.543765 ]
 [ 0.         0.         0.        ...  0.         0.         9.108469 ]
 [ 0.         0.         0.        ...  0.         0.         8.00188  ]]

In [12]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

### IG

In [13]:
PATH = '../Image/Sample/output/IGimgFeatureVec.csv'
SAVE_NAME = 'IGimg'

In [14]:
df = pd.read_csv(PATH, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,247,248,249,250,251,252,253,254,255,256
0,21bridgesmovie_17239.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.573396
1,21bridgesmovie_17240.jpg,0.000000,0.0,0.0,6.402988,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.378065
2,21bridgesmovie_17241.jpg,0.000000,0.0,0.0,1.087315,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.689849
3,21bridgesmovie_17242.jpg,0.000000,0.0,0.0,1.142214,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.632139
4,21bridgesmovie_17243.jpg,0.000000,0.0,0.0,1.679773,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.076295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30334,zombieland_5575.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.305132
30335,zombieland_5576.jpg,8.601309,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.551939
30336,zombieland_5577.jpg,1.387509,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.008000
30337,zombieland_5578.jpg,4.216678,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.249840
30338,zombieland_5579.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.293163

In [15]:
df['username'] = [string.split('_')[0] for string in df[0]]
df

,0,1,2,3,4,5,6,7,8,9,...,248,249,250,251,252,253,254,255,256,username
0,21bridgesmovie_17239.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.573396,21bridgesmovie
1,21bridgesmovie_17240.jpg,0.000000,0.0,0.0,6.402988,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.378065,21bridgesmovie
2,21bridgesmovie_17241.jpg,0.000000,0.0,0.0,1.087315,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.689849,21bridgesmovie
3,21bridgesmovie_17242.jpg,0.000000,0.0,0.0,1.142214,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.632139,21bridgesmovie
4,21bridgesmovie_17243.jpg,0.000000,0.0,0.0,1.679773,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.076295,21bridgesmovie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30334,zombieland_5575.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.305132,zombieland
30335,zombieland_5576.jpg,8.601309,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.551939,zombieland
30336,zombieland_5577.jpg,1.387509,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.008000,zombieland
30337,zombieland_5578.jpg,4.216678,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.249840,zombieland
30338,zombieland_5579.jpg,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.293163,zombieland

In [16]:
group = df.groupby('username').mean()
group.to_csv('../Image/Sample/output/IGimgFeatureVec_group.csv')
group

,1,2,3,4,5,6,7,8,9,10,...,247,248,249,250,251,252,253,254,255,256
username,,,,,,,,,,,,,,,,,,,,,
21bridgesmovie,0.012434,0.0,0.0,4.225312,0.202035,0.0,0.000000,0.000000,0.667585,0.0,...,0.0,0.062109,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,11.942448
47metersdown,0.190728,0.0,0.0,0.083620,0.000000,0.0,0.000000,0.234507,1.638160,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,14.029485
abeautifuldaymovie,0.195542,0.0,0.0,0.096402,0.008449,0.0,0.000000,0.298644,0.086082,0.0,...,0.0,0.044301,0.0,0.0,0.0,0.0,0.012299,0.000000,0.0,5.792375
abominablemovie,6.742114,0.0,0.0,0.020203,0.034986,0.0,0.011339,5.743747,0.041652,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.125800,0.0,10.254924
adastramovie,0.430505,0.0,0.0,0.047740,0.003781,0.0,0.008430,0.050995,0.692299,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.029425,0.002534,0.0,11.791386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wrinklestheclown,1.364438,0.0,0.0,0.070048,0.000000,0.0,0.167766,0.818350,1.492495,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.025897,2.436795,0.0,9.491776
xmenmovies,8.745901,0.0,0.0,0.767519,0.054254,0.0,0.026835,0.208496,0.690529,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.003729,0.000000,0.0,20.023428
yardiefilm,0.052559,0.0,0.0,1.361762,0.000000,0.0,0.000000,0.242347,0.683293,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.007698,0.000000,0.0,14.226838
yesterdaymovie,1.080159,0.0,0.0,0.008573,0.000000,0.0,0.000000,1.726636,0.141829,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.087907,1.823434,0.0,6.286044
zombieland,1.071063,0.0,0.0,0.071861,0.028982,0.0,0.000000,0.322737,0.113727,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.008669,0.371051,0.0,14.419264

In [17]:
npy = group.to_numpy()
print(npy.shape, npy)

(166, 256) [[1.24341125e-02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.19424481e+01]
 [1.90728444e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.40294853e+01]
 [1.95541520e-01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 5.79237461e+00]
 ...
 [5.25593437e-02 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.42268383e+01]
 [1.08015921e+00 0.00000000e+00 0.00000000e+00 ... 1.82343385e+00
  0.00000000e+00 6.28604381e+00]
 [1.07106252e+00 0.00000000e+00 0.00000000e+00 ... 3.71051081e-01
  0.00000000e+00 1.44192636e+01]]

In [18]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Video

# Movie genre

In [19]:
PATH = '../genresMat.csv'
SAVE_NAME = 'movie_genre'

In [20]:
df = pd.read_csv(PATH)
df

,movie,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,...,History,Horror,Music,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,21bridgesmovie,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,47metersdown,0,1,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
2,abeautifuldaymovie,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,abominablemovie,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,adastramovie,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,wrinklestheclown,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
162,xmenmovies,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
163,yardiefilm,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
164,yesterdaymovie,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
165,zombieland,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [21]:
df = df.iloc[:, 1:]
df

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,History,Horror,Music,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0
162,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
163,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
164,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
165,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [22]:
npy = df.to_numpy()
print(npy.shape, npy)

(166, 20) [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]

In [23]:
np.save('./npy/' + SAVE_NAME + '.npy', npy)

# User preference

## User following

## User genre