# Turn vector csv into npy

In [1]:
# Basic import
import os
import sys
import json
import shutil
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Helper function
def writeProgress(msg, count, total):
    sys.stdout.write(msg + "{:.2%}\r".format(count/total))
    sys.stdout.flush()
    
def newPath(path):
    if not os.path.isdir(path):
        os.mkdir(path)

def read_json(src_path):
    with open(src_path, 'r') as json_file:
        data = json.load(json_file)
    return data

def write_json(data,dst_path):
    with open(dst_path, 'w') as outfile:
        json.dump(data, outfile)

def writeLog(row):
    with open('log.txt', 'a') as outfile:
        outfile.write(row + '\n')

def getErrMsg(e):
    error_class = e.__class__.__name__ #取得錯誤類型
    detail = e.args[0] #取得詳細內容
    errMsg = "[{}] {}".format(error_class, detail)
    return errMsg

# Feature

## Text

In [3]:
PATH = '../Text/output/TextFeatureVec.csv'
SAVE_NAME = 'text'

In [4]:
df = pd.read_csv(PATH, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,291,292,293,294,295,296,297,298,299,300
0,21bridgesmovie,4.625625,0.270240,0.843757,0.361738,0.385804,0.386609,1.417814,3.703098,1.964221,...,0.518959,1.518856,1.617028,0.689357,0.253527,0.424694,3.344936,3.522084,0.689225,2.659301
1,47metersdown,1.227327,1.386205,1.245207,0.483765,1.854537,1.861350,1.422121,1.313766,1.073333,...,2.369604,0.415461,2.303477,1.855965,0.722303,0.954403,1.338140,0.958282,1.601425,1.273016
2,abeautifuldaymovie,0.302373,0.038617,0.328554,0.393081,0.214754,0.233469,0.234261,0.317635,2.241514,...,1.382313,0.505444,0.411402,1.813654,0.109178,0.619214,4.462339,0.545749,0.698804,2.974110
3,abominablemovie,0.186162,0.000000,0.089363,0.246190,0.235176,0.256702,0.428070,0.513695,0.565004,...,0.586406,0.315049,0.432583,1.190027,0.128935,0.620930,0.421282,0.109546,0.694254,0.206418
4,adastramovie,3.830110,1.397172,1.287266,0.298948,1.933444,2.106336,2.286842,2.996085,1.740809,...,1.833267,1.069029,3.520368,0.546656,1.459306,0.568826,2.526160,2.906972,1.745568,2.181656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,wrinklestheclown,0.853294,0.896881,0.000000,1.337605,1.505762,1.014642,0.112749,0.271832,0.412343,...,1.331714,1.854079,0.000000,1.670097,0.958906,0.974099,0.554800,0.130257,0.475131,0.115792
161,xmenmovies,2.842772,0.806930,5.102901,0.388758,1.401573,1.073662,4.430752,5.804434,0.536433,...,0.906498,0.570307,9.188423,1.268965,0.614569,2.790452,1.126672,3.803742,7.926337,0.756108
162,yardiefilm,2.580427,0.371021,0.258102,1.061416,0.314597,0.228967,0.332296,2.102141,2.003907,...,1.032518,2.002433,0.319524,1.297553,0.279873,1.396268,3.653067,2.020441,0.691687,2.927576
163,yesterdaymovie,1.098065,1.916392,0.428723,0.717684,1.611092,1.348285,0.459656,0.504291,0.889729,...,3.017361,1.263357,0.501066,1.724245,1.742528,0.652188,1.596182,0.407870,0.948900,0.851927
164,zombieland,4.156315,2.123129,3.339168,1.519991,2.271654,1.795395,3.109476,4.125190,0.895719,...,1.640270,2.695757,6.212105,0.800507,2.376627,1.591925,1.297943,2.721867,5.013988,0.995655

In [5]:
df = df.loc[:, 1:]
df

,1,2,3,4,5,6,7,8,9,10,...,291,292,293,294,295,296,297,298,299,300
0,4.625625,0.270240,0.843757,0.361738,0.385804,0.386609,1.417814,3.703098,1.964221,0.340831,...,0.518959,1.518856,1.617028,0.689357,0.253527,0.424694,3.344936,3.522084,0.689225,2.659301
1,1.227327,1.386205,1.245207,0.483765,1.854537,1.861350,1.422121,1.313766,1.073333,1.669586,...,2.369604,0.415461,2.303477,1.855965,0.722303,0.954403,1.338140,0.958282,1.601425,1.273016
2,0.302373,0.038617,0.328554,0.393081,0.214754,0.233469,0.234261,0.317635,2.241514,0.386934,...,1.382313,0.505444,0.411402,1.813654,0.109178,0.619214,4.462339,0.545749,0.698804,2.974110
3,0.186162,0.000000,0.089363,0.246190,0.235176,0.256702,0.428070,0.513695,0.565004,0.521737,...,0.586406,0.315049,0.432583,1.190027,0.128935,0.620930,0.421282,0.109546,0.694254,0.206418
4,3.830110,1.397172,1.287266,0.298948,1.933444,2.106336,2.286842,2.996085,1.740809,1.958116,...,1.833267,1.069029,3.520368,0.546656,1.459306,0.568826,2.526160,2.906972,1.745568,2.181656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,0.853294,0.896881,0.000000,1.337605,1.505762,1.014642,0.112749,0.271832,0.412343,0.873156,...,1.331714,1.854079,0.000000,1.670097,0.958906,0.974099,0.554800,0.130257,0.475131,0.115792
161,2.842772,0.806930,5.102901,0.388758,1.401573,1.073662,4.430752,5.804434,0.536433,0.629329,...,0.906498,0.570307,9.188423,1.268965,0.614569,2.790452,1.126672,3.803742,7.926337,0.756108
162,2.580427,0.371021,0.258102,1.061416,0.314597,0.228967,0.332296,2.102141,2.003907,0.501374,...,1.032518,2.002433,0.319524,1.297553,0.279873,1.396268,3.653067,2.020441,0.691687,2.927576
163,1.098065,1.916392,0.428723,0.717684,1.611092,1.348285,0.459656,0.504291,0.889729,2.496572,...,3.017361,1.263357,0.501066,1.724245,1.742528,0.652188,1.596182,0.407870,0.948900,0.851927
164,4.156315,2.123129,3.339168,1.519991,2.271654,1.795395,3.109476,4.125190,0.895719,1.967186,...,1.640270,2.695757,6.212105,0.800507,2.376627,1.591925,1.297943,2.721867,5.013988,0.995655

In [6]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 300) [[4.625625   0.27023974 0.8437569  ... 3.5220842  0.6892248  2.659301  ]
 [1.2273268  1.3862046  1.245207   ... 0.95828235 1.6014247  1.2730157 ]
 [0.30237263 0.03861726 0.32855368 ... 0.5457492  0.6988041  2.9741096 ]
 ...
 [2.5804267  0.37102053 0.25810206 ... 2.020441   0.69168675 2.9275765 ]
 [1.0980647  1.916392   0.42872304 ... 0.40786976 0.9488999  0.85192657]
 [4.156315   2.1231294  3.3391676  ... 2.7218666  5.0139885  0.99565506]]

In [ ]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Image

### Poster

In [7]:
PATH = '../Image/Sample/output/PosterFeatureVec.csv'
SAVE_NAME = 'poster'

In [8]:
df = pd.read_csv(PATH, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048
0,21bridgesmovie.jpg,0.494758,0.283308,0.065662,0.000000,0.335951,0.031979,0.301165,2.045833,0.208562,...,0.000000,0.000000,1.193770,1.506646,0.315323,0.583171,0.002632,0.087382,0.069765,0.469502
1,47metersdown.jpg,1.519427,0.806621,0.126966,0.261728,0.000000,0.108213,0.196652,0.459518,0.259999,...,0.000000,0.460017,1.057664,0.163948,0.223188,0.069748,0.103279,2.986067,0.276734,0.512829
2,abeautifuldaymovie.jpg,0.077306,0.613698,0.102838,0.396761,0.265735,0.039994,0.629388,2.077992,0.590141,...,0.274793,1.088040,0.124551,0.122737,0.225596,0.015422,0.000000,0.436052,0.676374,0.143547
3,abominablemovie.jpg,0.069226,0.056583,0.371933,0.749337,0.059648,0.569080,0.043452,0.031216,0.071888,...,0.026392,0.000000,0.000000,0.038951,1.083343,0.126524,0.093844,0.000000,0.523096,0.034955
4,adastramovie.jpg,0.729522,0.164893,0.260869,0.015868,0.100866,0.313320,0.070898,0.394072,0.166367,...,0.021538,0.587754,0.927968,0.098810,0.000000,0.084116,0.711746,0.378344,0.000000,0.066408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,wrinklestheclown.jpg,0.199897,0.671948,0.000000,0.019108,0.279197,0.039664,0.235553,0.322959,0.146369,...,0.146693,0.415582,0.784930,0.020980,0.000000,0.000000,0.190380,0.088201,0.000000,0.554774
161,xmenmovies.jpg,3.063733,1.313999,0.694954,0.000000,0.115780,0.000000,0.537104,0.685775,0.888244,...,0.058512,0.557968,0.620168,0.021954,0.758886,1.129855,0.037468,0.134155,0.137868,2.214420
162,yardiefilm.jpg,0.587885,0.451792,0.024987,0.018251,1.819033,0.144624,0.173273,0.414593,0.040721,...,0.287570,0.136541,3.389530,2.044187,0.060037,0.392755,0.274924,0.243140,0.000000,0.056881
163,yesterdaymovie.jpg,0.027935,0.425899,0.004879,0.141607,1.314379,0.013914,0.053892,0.488039,0.114076,...,0.449295,0.055668,0.644438,0.973870,0.615937,0.005609,0.004708,0.195625,0.029894,0.459155
164,zombieland.jpg,0.802443,0.266962,1.947216,0.000845,0.674209,0.034047,0.146127,0.641236,0.057742,...,0.000000,0.044277,0.059140,1.136499,0.740328,0.181827,0.194591,0.105939,0.632977,0.018494

In [9]:
df = df.loc[:, 1:]
df

,1,2,3,4,5,6,7,8,9,10,...,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048
0,0.494758,0.283308,0.065662,0.000000,0.335951,0.031979,0.301165,2.045833,0.208562,0.941920,...,0.000000,0.000000,1.193770,1.506646,0.315323,0.583171,0.002632,0.087382,0.069765,0.469502
1,1.519427,0.806621,0.126966,0.261728,0.000000,0.108213,0.196652,0.459518,0.259999,1.053462,...,0.000000,0.460017,1.057664,0.163948,0.223188,0.069748,0.103279,2.986067,0.276734,0.512829
2,0.077306,0.613698,0.102838,0.396761,0.265735,0.039994,0.629388,2.077992,0.590141,0.050286,...,0.274793,1.088040,0.124551,0.122737,0.225596,0.015422,0.000000,0.436052,0.676374,0.143547
3,0.069226,0.056583,0.371933,0.749337,0.059648,0.569080,0.043452,0.031216,0.071888,0.186235,...,0.026392,0.000000,0.000000,0.038951,1.083343,0.126524,0.093844,0.000000,0.523096,0.034955
4,0.729522,0.164893,0.260869,0.015868,0.100866,0.313320,0.070898,0.394072,0.166367,0.147495,...,0.021538,0.587754,0.927968,0.098810,0.000000,0.084116,0.711746,0.378344,0.000000,0.066408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,0.199897,0.671948,0.000000,0.019108,0.279197,0.039664,0.235553,0.322959,0.146369,1.392606,...,0.146693,0.415582,0.784930,0.020980,0.000000,0.000000,0.190380,0.088201,0.000000,0.554774
161,3.063733,1.313999,0.694954,0.000000,0.115780,0.000000,0.537104,0.685775,0.888244,0.266433,...,0.058512,0.557968,0.620168,0.021954,0.758886,1.129855,0.037468,0.134155,0.137868,2.214420
162,0.587885,0.451792,0.024987,0.018251,1.819033,0.144624,0.173273,0.414593,0.040721,0.121475,...,0.287570,0.136541,3.389530,2.044187,0.060037,0.392755,0.274924,0.243140,0.000000,0.056881
163,0.027935,0.425899,0.004879,0.141607,1.314379,0.013914,0.053892,0.488039,0.114076,0.150991,...,0.449295,0.055668,0.644438,0.973870,0.615937,0.005609,0.004708,0.195625,0.029894,0.459155
164,0.802443,0.266962,1.947216,0.000845,0.674209,0.034047,0.146127,0.641236,0.057742,0.345229,...,0.000000,0.044277,0.059140,1.136499,0.740328,0.181827,0.194591,0.105939,0.632977,0.018494

In [10]:
poster_npy = df.to_numpy()
print(poster_npy.shape, poster_npy)

(165, 2048) [[0.49475807 0.28330824 0.06566165 ... 0.08738196 0.06976548 0.469502  ]
 [1.5194275  0.80662096 0.12696646 ... 2.9860668  0.2767335  0.512829  ]
 [0.07730576 0.6136975  0.10283829 ... 0.43605196 0.6763744  0.14354736]
 ...
 [0.5878847  0.45179185 0.02498718 ... 0.2431399  0.         0.05688086]
 [0.02793477 0.42589915 0.0048787  ... 0.19562516 0.02989419 0.45915523]
 [0.8024434  0.26696184 1.9472163  ... 0.10593923 0.6329765  0.01849403]]

In [ ]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

### IG

In [11]:
PATH = '../Image/Sample/output/IGimgFeatureVec.csv'
SAVE_NAME = 'IGimg'

In [12]:
df = pd.read_csv(PATH, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048
0,21bridgesmovie_22217.jpg,0.331813,0.334793,0.020973,0.069121,1.450596,0.712886,0.480257,2.208983,0.162940,...,0.056089,0.797267,2.800650,3.000357,1.523949,0.498544,0.071483,0.768686,0.021901,0.038476
1,21bridgesmovie_22218.jpg,0.130291,1.547714,0.000000,0.073273,0.078071,0.000000,0.070401,0.289346,1.153553,...,0.249781,0.349757,2.192273,0.376216,0.488646,0.094902,0.612856,1.569600,0.080053,0.332811
2,21bridgesmovie_22219.jpg,0.740051,0.824680,0.251876,0.419343,1.076743,0.000000,0.213411,1.576596,0.005514,...,0.058990,0.071405,2.646841,1.244074,0.219941,0.082223,0.207473,0.020224,0.100037,0.711623
3,21bridgesmovie_22220.jpg,0.025813,0.771999,0.054810,0.051743,0.039484,0.000000,0.156691,0.859746,0.019721,...,0.000000,0.445953,1.831583,0.183303,0.152106,0.255341,1.063585,1.252706,0.332302,0.199079
4,21bridgesmovie_22221.jpg,0.090466,0.000000,0.128749,0.238021,0.595631,0.050999,0.455349,1.931511,0.207198,...,0.134479,0.945805,0.132786,0.873131,0.120998,0.000000,0.002045,0.448773,0.229544,0.125882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37954,zombieland_7839.jpg,0.088361,0.302754,0.001350,0.164013,0.895509,0.000000,0.053063,0.329108,0.000000,...,0.164409,0.034488,0.118139,1.469632,0.608908,0.141757,0.040633,0.111562,0.066248,0.667725
37955,zombieland_7840.jpg,0.182120,0.010173,0.311166,0.024346,1.038138,0.094662,0.041859,0.491167,0.170245,...,0.000000,0.154903,0.068876,1.120993,0.730786,0.363519,0.074791,0.096592,0.128792,0.585530
37956,zombieland_7841.jpg,0.040291,0.915755,0.070129,0.016132,0.109926,0.310837,0.000000,0.000000,0.476589,...,0.000000,0.076708,0.338057,0.531682,0.128355,0.000000,0.002735,1.048143,0.076546,0.056163
37957,zombieland_7842.jpg,0.048829,0.411975,0.000000,0.000000,1.094483,0.074808,0.178307,0.607130,0.002279,...,0.000000,0.132978,0.405171,1.677894,0.123480,0.112938,0.000000,0.083492,0.043363,0.289784
37958,zombieland_7843.jpg,0.161385,0.521045,1.093487,0.549951,2.184265,1.169457,0.033490,0.336400,0.232571,...,0.333437,0.124930,0.005909,0.558952,1.602938,0.012159,0.064567,0.308352,0.669774,0.769733

In [13]:
df['username'] = [string.split('_')[0] for string in df[0]]
df

,0,1,2,3,4,5,6,7,8,9,...,2040,2041,2042,2043,2044,2045,2046,2047,2048,username
0,21bridgesmovie_22217.jpg,0.331813,0.334793,0.020973,0.069121,1.450596,0.712886,0.480257,2.208983,0.162940,...,0.797267,2.800650,3.000357,1.523949,0.498544,0.071483,0.768686,0.021901,0.038476,21bridgesmovie
1,21bridgesmovie_22218.jpg,0.130291,1.547714,0.000000,0.073273,0.078071,0.000000,0.070401,0.289346,1.153553,...,0.349757,2.192273,0.376216,0.488646,0.094902,0.612856,1.569600,0.080053,0.332811,21bridgesmovie
2,21bridgesmovie_22219.jpg,0.740051,0.824680,0.251876,0.419343,1.076743,0.000000,0.213411,1.576596,0.005514,...,0.071405,2.646841,1.244074,0.219941,0.082223,0.207473,0.020224,0.100037,0.711623,21bridgesmovie
3,21bridgesmovie_22220.jpg,0.025813,0.771999,0.054810,0.051743,0.039484,0.000000,0.156691,0.859746,0.019721,...,0.445953,1.831583,0.183303,0.152106,0.255341,1.063585,1.252706,0.332302,0.199079,21bridgesmovie
4,21bridgesmovie_22221.jpg,0.090466,0.000000,0.128749,0.238021,0.595631,0.050999,0.455349,1.931511,0.207198,...,0.945805,0.132786,0.873131,0.120998,0.000000,0.002045,0.448773,0.229544,0.125882,21bridgesmovie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37954,zombieland_7839.jpg,0.088361,0.302754,0.001350,0.164013,0.895509,0.000000,0.053063,0.329108,0.000000,...,0.034488,0.118139,1.469632,0.608908,0.141757,0.040633,0.111562,0.066248,0.667725,zombieland
37955,zombieland_7840.jpg,0.182120,0.010173,0.311166,0.024346,1.038138,0.094662,0.041859,0.491167,0.170245,...,0.154903,0.068876,1.120993,0.730786,0.363519,0.074791,0.096592,0.128792,0.585530,zombieland
37956,zombieland_7841.jpg,0.040291,0.915755,0.070129,0.016132,0.109926,0.310837,0.000000,0.000000,0.476589,...,0.076708,0.338057,0.531682,0.128355,0.000000,0.002735,1.048143,0.076546,0.056163,zombieland
37957,zombieland_7842.jpg,0.048829,0.411975,0.000000,0.000000,1.094483,0.074808,0.178307,0.607130,0.002279,...,0.132978,0.405171,1.677894,0.123480,0.112938,0.000000,0.083492,0.043363,0.289784,zombieland
37958,zombieland_7843.jpg,0.161385,0.521045,1.093487,0.549951,2.184265,1.169457,0.033490,0.336400,0.232571,...,0.124930,0.005909,0.558952,1.602938,0.012159,0.064567,0.308352,0.669774,0.769733,zombieland

In [14]:
group = df.groupby('username').mean()
group.to_csv('../Image/Sample/output/IGimgFeatureVec_group.csv')
group

,1,2,3,4,5,6,7,8,9,10,...,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048
username,,,,,,,,,,,,,,,,,,,,,
21bridgesmovie,0.493511,0.456718,0.159513,0.139757,0.733778,0.283911,0.178954,1.588011,0.426711,0.131176,...,0.163705,0.445806,2.073926,1.778595,0.391657,0.208094,0.311020,0.656493,0.252922,0.261573
47metersdown,0.959267,0.450579,0.138192,0.221089,0.196270,0.175800,0.284615,0.359620,0.072881,0.403770,...,0.193652,0.575036,0.692117,0.278784,0.220668,0.112783,0.182530,1.061706,0.228888,0.327805
abeautifuldaymovie,0.216008,0.665498,0.140317,0.519259,0.331685,0.123064,0.967564,1.409957,0.271901,0.356101,...,0.629256,0.614837,0.822323,0.851326,0.318444,0.025505,0.109678,0.762225,0.390723,0.397177
abominablemovie,0.321312,0.249236,0.156039,0.842645,0.451429,0.310091,0.111814,0.109763,0.198508,0.180987,...,0.237197,0.197429,0.120572,0.199731,0.641133,0.063515,0.170164,0.213464,0.450424,0.173634
adastramovie,0.535617,0.354574,0.336503,0.142333,0.413927,0.300933,0.239407,0.477948,0.205328,0.298817,...,0.268620,1.134822,0.802182,0.431821,0.398653,0.080874,0.148955,0.913962,0.400167,0.327246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wrinklestheclown,0.420413,0.905093,0.059553,0.353043,0.186951,0.281562,0.151260,0.087675,0.135054,0.647792,...,0.172867,0.345677,0.333366,0.122942,0.110897,0.059047,0.427274,0.275375,0.103697,0.238406
xmenmovies,0.533515,0.527889,0.380976,0.224500,0.256823,0.074202,0.335687,0.862431,0.354468,0.684171,...,0.388859,0.528630,0.783260,0.637888,0.442711,0.156306,0.227469,0.321024,0.789155,0.341580
yardiefilm,0.570591,0.523850,0.269837,0.205206,0.609369,0.265700,0.276377,0.705793,0.134432,0.218250,...,0.312322,0.257836,1.068061,1.087042,0.238596,0.100592,0.172321,0.510214,0.343606,0.232004
yesterdaymovie,0.241110,0.268485,0.169761,0.152681,0.862261,0.161442,0.633406,0.235377,0.210424,0.148196,...,0.659321,0.155542,0.224081,0.437979,0.242450,0.044548,0.099211,0.245290,0.265239,0.665381
zombieland,0.319944,0.316458,0.212092,0.187379,0.737168,0.163008,0.164325,0.324855,0.234254,0.281722,...,0.338249,0.314066,0.371568,0.758299,0.392903,0.109446,0.094622,0.448191,0.247054,0.298940

In [15]:
IG_npy = group.to_numpy()
print(IG_npy.shape, IG_npy)

(165, 2048) [[0.4935109  0.45671789 0.15951251 ... 0.65649261 0.25292226 0.26157303]
 [0.95926712 0.45057878 0.13819194 ... 1.06170623 0.22888842 0.32780538]
 [0.21600796 0.66549798 0.14031741 ... 0.7622245  0.39072257 0.39717658]
 ...
 [0.57059085 0.52384985 0.26983693 ... 0.51021401 0.34360608 0.23200411]
 [0.2411104  0.26848473 0.16976135 ... 0.24529025 0.265239   0.66538086]
 [0.31994406 0.31645807 0.21209246 ... 0.44819088 0.24705376 0.2989397 ]]

In [ ]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

### Merge image feature

In [ ]:
SAVE_NAME = "image"

In [ ]:
npy = (poster_npy + IG_npy) / 2
print(npy.shape, npy)

In [ ]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Video

In [16]:
PATH = '../Video/csv/computed_minmaxnorm_2019_log.csv'
SAVE_NAME = 'video'

In [17]:
df = pd.read_csv(PATH)
df

,Movie,A_avg,A_std,B_avg,B_std,C_avg,C_std,D_avg,D_std,A_avg_minmaxnorm,A_std_minmaxnorm,B_avg_minmaxnorm,B_std_minmaxnorm,C_avg_minmaxnorm,C_std_minmaxnorm,D_avg_minmaxnorm,D_std_minmaxnorm
0,21bridgesmovie,3.518647,3.413387,13.907436,15.439361,0.186758,0.245622,7.270932,7.083156,0.064317,0.212065,0.425476,0.512305,0.303963,0.455250,0.029611,0.013163
1,47metersdown,3.549758,3.171456,16.295219,17.237230,0.245609,0.249743,8.251181,8.097400,0.073366,0.153932,0.661132,0.679877,0.471069,0.471811,0.588256,0.853833
2,abeautifuldaymovie,3.743390,3.729937,14.801673,15.869060,0.237930,0.307260,8.239522,7.781294,0.129683,0.288129,0.513731,0.552355,0.449266,0.702974,0.581612,0.591825
3,abominablemovie,3.487348,3.274070,17.482964,18.210801,0.251836,0.284515,8.498778,7.970775,0.055214,0.178589,0.778354,0.770619,0.488753,0.611561,0.729362,0.748879
4,adastramovie,4.081181,4.021839,13.771053,14.892246,0.253118,0.300952,8.075115,7.784539,0.227927,0.358270,0.412016,0.461310,0.492392,0.677623,0.487916,0.594514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,wrinklestheclown,3.674363,3.291100,16.343698,17.367981,0.218662,0.281909,8.255468,8.273745,0.109606,0.182681,0.665917,0.692064,0.394556,0.601089,0.590700,1.000000
161,xmenmovies,3.726881,3.525028,15.382260,16.515194,0.319549,0.279627,7.990810,7.741344,0.124881,0.238892,0.571030,0.612579,0.681022,0.591916,0.439871,0.558712
162,yardiefilm,3.705499,3.711716,13.653330,14.709328,0.176796,0.197451,7.693021,7.423313,0.118662,0.283751,0.400398,0.444261,0.275676,0.261650,0.270160,0.295108
163,yesterdaymovie,3.462233,3.155266,16.416116,17.207047,0.180151,0.253020,8.418139,8.124500,0.047910,0.150041,0.673064,0.677064,0.285204,0.484984,0.683406,0.876296
164,zombieland,3.620412,3.433065,16.049908,16.704344,0.287000,0.305738,8.530966,8.010033,0.093915,0.216794,0.636922,0.630209,0.588598,0.696858,0.747707,0.781419

In [18]:
df = df.iloc[:, 9:]
df

,A_avg_minmaxnorm,A_std_minmaxnorm,B_avg_minmaxnorm,B_std_minmaxnorm,C_avg_minmaxnorm,C_std_minmaxnorm,D_avg_minmaxnorm,D_std_minmaxnorm
0,0.064317,0.212065,0.425476,0.512305,0.303963,0.455250,0.029611,0.013163
1,0.073366,0.153932,0.661132,0.679877,0.471069,0.471811,0.588256,0.853833
2,0.129683,0.288129,0.513731,0.552355,0.449266,0.702974,0.581612,0.591825
3,0.055214,0.178589,0.778354,0.770619,0.488753,0.611561,0.729362,0.748879
4,0.227927,0.358270,0.412016,0.461310,0.492392,0.677623,0.487916,0.594514
...,...,...,...,...,...,...,...,...
160,0.109606,0.182681,0.665917,0.692064,0.394556,0.601089,0.590700,1.000000
161,0.124881,0.238892,0.571030,0.612579,0.681022,0.591916,0.439871,0.558712
162,0.118662,0.283751,0.400398,0.444261,0.275676,0.261650,0.270160,0.295108
163,0.047910,0.150041,0.673064,0.677064,0.285204,0.484984,0.683406,0.876296
164,0.093915,0.216794,0.636922,0.630209,0.588598,0.696858,0.747707,0.781419

In [19]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 8) [[0.06431727 0.21206534 0.42547612 ... 0.45525045 0.02961095 0.01316341]
 [0.07336566 0.15393189 0.66113249 ... 0.47181116 0.58825642 0.85383342]
 [0.12968256 0.28812912 0.51373062 ... 0.70297361 0.58161191 0.59182537]
 ...
 [0.11866202 0.28375068 0.40039768 ... 0.26164951 0.2701602  0.29510787]
 [0.04790979 0.15004138 0.6730642  ... 0.48498426 0.68340588 0.87629614]
 [0.09391496 0.21679366 0.6369222  ... 0.6968582  0.74770654 0.78141881]]

In [ ]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Follow

In [20]:
PATH = '../Autoencoder/output/grid/80-10dim.csv'
SAVE_NAME = 'follow'

In [21]:
df = pd.read_csv(PATH)
df

,movie,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9
0,21bridgesmovie,1.313291,1.413283,1.544461,1.886759,1.728442,0.000000,1.137120,1.510174,0.978163,1.822727
1,47metersdown,0.837493,0.905968,1.373671,1.346066,1.459658,0.000000,0.565606,1.517898,0.007892,1.391771
2,abeautifuldaymovie,1.062834,1.609145,1.423535,1.532653,1.381293,0.000000,1.040888,1.345244,0.888910,1.047465
3,abominablemovie,1.119693,1.546281,0.241988,1.136334,1.616928,0.000000,0.707046,0.821275,0.929626,0.747105
4,adastramovie,1.365520,0.578039,1.282238,1.432905,1.270007,0.094023,0.953967,1.771913,0.411324,1.990719
...,...,...,...,...,...,...,...,...,...,...,...
160,wrinklestheclown,0.751404,0.784730,0.843319,0.931058,0.829312,0.000000,0.719121,0.997329,0.524739,0.931197
161,xmenmovies,0.680980,1.059782,1.427396,1.851414,1.099045,0.000000,1.039739,0.825713,0.891358,1.306172
162,yardiefilm,1.058341,1.289066,1.350711,1.435796,1.171857,0.000000,1.037003,1.555916,0.771497,1.444147
163,yesterdaymovie,1.181066,1.273515,1.553790,1.594873,1.626290,0.000000,0.995866,1.313411,0.817974,1.134134
164,zombieland,0.156272,3.202521,1.255736,1.322427,1.222130,0.000000,1.043058,0.305793,1.542696,0.195504

In [22]:
df = df.iloc[:, 1:]
df

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9
0,1.313291,1.413283,1.544461,1.886759,1.728442,0.000000,1.137120,1.510174,0.978163,1.822727
1,0.837493,0.905968,1.373671,1.346066,1.459658,0.000000,0.565606,1.517898,0.007892,1.391771
2,1.062834,1.609145,1.423535,1.532653,1.381293,0.000000,1.040888,1.345244,0.888910,1.047465
3,1.119693,1.546281,0.241988,1.136334,1.616928,0.000000,0.707046,0.821275,0.929626,0.747105
4,1.365520,0.578039,1.282238,1.432905,1.270007,0.094023,0.953967,1.771913,0.411324,1.990719
...,...,...,...,...,...,...,...,...,...,...
160,0.751404,0.784730,0.843319,0.931058,0.829312,0.000000,0.719121,0.997329,0.524739,0.931197
161,0.680980,1.059782,1.427396,1.851414,1.099045,0.000000,1.039739,0.825713,0.891358,1.306172
162,1.058341,1.289066,1.350711,1.435796,1.171857,0.000000,1.037003,1.555916,0.771497,1.444147
163,1.181066,1.273515,1.553790,1.594873,1.626290,0.000000,0.995866,1.313411,0.817974,1.134134
164,0.156272,3.202521,1.255736,1.322427,1.222130,0.000000,1.043058,0.305793,1.542696,0.195504

In [23]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 10) [[1.3132908  1.4132833  1.5444614  ... 1.5101745  0.97816306 1.8227268 ]
 [0.8374928  0.9059681  1.3736712  ... 1.5178976  0.00789221 1.3917707 ]
 [1.062834   1.6091454  1.4235351  ... 1.3452443  0.8889104  1.0474652 ]
 ...
 [1.0583408  1.2890663  1.350711   ... 1.5559162  0.77149683 1.4441472 ]
 [1.1810656  1.2735145  1.5537901  ... 1.3134111  0.8179738  1.1341342 ]
 [0.15627183 3.2025208  1.2557362  ... 0.30579287 1.5426961  0.19550432]]

In [7]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

## Social

In [59]:
PATH = '../Social/social_norm.csv'
SAVE_NAME = 'social'

In [60]:
df = pd.read_csv(PATH)
df

,Account,tconst,averageRating,numVotes,Uid,Posts,Followers,Likes,Comments,averageRating_norm,numVotes_norm,Posts_norm,Followers_norm,Likes_norm,Comments_norm
0,21bridgesmovie,tt8688634,6.6,18694,8600709558,81,15595,73032,1468,0.66,0.026113,0.016297,0.001166,0.000189,0.000457
1,47metersdown,tt7329656,5.0,12683,4773990401,61,38297,234154,5986,0.50,0.017533,0.010954,0.002924,0.000628,0.001993
2,abeautifuldaymovie,tt3224458,7.4,29979,9457986739,133,32213,245879,3323,0.74,0.042220,0.030190,0.002453,0.000660,0.001087
3,abominablemovie,tt6324278,7.0,18487,8751027688,134,19847,152470,2489,0.70,0.025817,0.030457,0.001495,0.000405,0.000804
4,adastramovie,tt2935510,6.6,147914,8014594288,118,19262,349380,8189,0.66,0.210550,0.026182,0.001450,0.000942,0.002742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,wrinklestheclown,tt9097270,4.7,537,16149244607,72,19564,108787,3289,0.47,0.000197,0.013893,0.001473,0.000286,0.001076
161,xmenmovies,tt6565702,5.8,125765,401420930,1333,1036371,12189097,115918,0.58,0.178936,0.350788,0.080235,0.033188,0.039364
162,yardiefilm,tt5862902,5.8,2248,6552487116,47,6574,25558,1436,0.58,0.002639,0.007213,0.000467,0.000060,0.000446
163,yesterdaymovie,tt8079248,6.9,79700,10390112691,118,45500,500137,8931,0.69,0.113187,0.026182,0.003482,0.001352,0.002994
164,zombieland,tt1560220,6.8,87731,9139732106,151,97918,1013914,11326,0.68,0.124650,0.034999,0.007542,0.002751,0.003808

In [61]:
df = df.iloc[:, 9:]
df

,averageRating_norm,numVotes_norm,Posts_norm,Followers_norm,Likes_norm,Comments_norm
0,0.66,0.026113,0.016297,0.001166,0.000189,0.000457
1,0.50,0.017533,0.010954,0.002924,0.000628,0.001993
2,0.74,0.042220,0.030190,0.002453,0.000660,0.001087
3,0.70,0.025817,0.030457,0.001495,0.000405,0.000804
4,0.66,0.210550,0.026182,0.001450,0.000942,0.002742
...,...,...,...,...,...,...
160,0.47,0.000197,0.013893,0.001473,0.000286,0.001076
161,0.58,0.178936,0.350788,0.080235,0.033188,0.039364
162,0.58,0.002639,0.007213,0.000467,0.000060,0.000446
163,0.69,0.113187,0.026182,0.003482,0.001352,0.002994
164,0.68,0.124650,0.034999,0.007542,0.002751,0.003808

In [62]:
# # imdb
# df = df.iloc[:, :2]
# df
# IG
df = df.iloc[:, 2:]
df

     Posts_norm  Followers_norm  Likes_norm  Comments_norm
0      0.016297        0.001166    0.000189       0.000457
1      0.010954        0.002924    0.000628       0.001993
2      0.030190        0.002453    0.000660       0.001087
3      0.030457        0.001495    0.000405       0.000804
4      0.026182        0.001450    0.000942       0.002742
..          ...             ...         ...            ...
160    0.013893        0.001473    0.000286       0.001076
161    0.350788        0.080235    0.033188       0.039364
162    0.007213        0.000467    0.000060       0.000446
163    0.026182        0.003482    0.001352       0.002994
164    0.034999        0.007542    0.002751       0.003808

[165 rows x 4 columns]

In [63]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 4) [[1.62970879e-02 1.16561411e-03 1.88904463e-04 4.56889703e-04]
 [1.09537804e-02 2.92410503e-03 6.27732371e-04 1.99277339e-03]
 [3.01896874e-02 2.45284000e-03 6.59666292e-04 1.08749268e-03]
 [3.04568528e-02 1.49497290e-03 4.05259842e-04 8.03976300e-04]
 [2.61822068e-02 1.44965896e-03 9.41559064e-04 2.74167817e-03]
 [5.12957521e-02 4.58027164e-03 1.42849621e-03 3.80639435e-03]
 [8.28212664e-03 1.52130921e-04 3.75308684e-05 8.70266101e-05]
 [9.35078814e-03 1.77203011e-01 6.56199044e-02 1.56080865e-01]
 [4.54181138e-03 1.33772964e-04 1.97731571e-05 2.14167048e-05]
 [8.89660700e-02 1.00914544e-02 5.07712031e-03 8.79852626e-03]
 [5.26315789e-02 2.26747885e-03 5.03948595e-04 1.75888938e-03]
 [5.37002404e-02 2.79335299e-03 7.69728695e-04 2.44898320e-03]
 [8.46914240e-02 1.17519587e-02 4.50388668e-03 1.10051268e-02]
 [5.61047288e-03 8.27579818e-04 1.81305688e-04 4.92584211e-04]
 [2.67165375e-02 3.41132677e-04 4.77905767e-05 1.06063681e-04]
 [4.80897676e-03 5.34541891e-03 3.73647303e-05 4.79326251e-04]
 [6.14480363e-03 1.04183345e-04 3.69888769e-05 1.01984309e-04]
 [2.27090569e-02 1.38358580e-03 8.66995742e-04 2.03492691e-03]
 [9.51108736e-02 8.91517408e-01 3.30096385e-01 2.21947431e-01]
 [2.72508683e-02 7.49035646e-04 2.62598965e-04 1.26154590e-03]
 [3.71359872e-02 6.12938890e-04 3.10114460e-04 1.11536839e-03]
 [2.75180337e-02 1.08389408e-03 1.25456051e-04 5.02442694e-04]
 [9.08362276e-03 9.97449019e-04 6.66445271e-04 2.50677431e-03]
 [1.73657494e-02 5.07128891e-04 9.33614395e-05 2.78077215e-04]
 [2.21747262e-02 2.55253068e-03 4.48970503e-04 9.83808631e-04]
 [4.54181138e-02 3.09265741e-03 2.32917985e-03 4.61988918e-03]
 [6.33181940e-02 3.00536029e-03 1.02882787e-03 1.80444237e-03]
 [2.19075608e-02 1.07901412e-03 5.82259557e-04 8.02956457e-04]
 [2.05717339e-02 1.77003242e-03 5.81172850e-04 1.81906012e-03]
 [1.81672455e-02 7.81956033e-04 4.22404749e-04 1.36760958e-03]
 [6.17152017e-02 8.43274709e-02 1.73617988e-02 1.79818733e-02]
 [1.62970879e-02 1.94656316e-04 2.22379928e-05 1.00964466e-04]
 [7.48063051e-03 6.63008863e-03 1.67692986e-03 6.43452998e-03]
 [3.87389794e-02 2.09315571e-02 1.02047929e-02 1.14076248e-02]
 [2.93881913e-02 7.26061088e-03 1.18296861e-02 3.69057417e-02]
 [5.18300828e-02 3.09614310e-03 7.83185881e-04 1.80920164e-03]
 [7.48063051e-03 7.54457827e-05 1.50886075e-05 9.62051979e-05]
 [9.61795351e-03 2.42015199e-03 4.89015231e-04 1.91560526e-03]
 [9.35078814e-03 9.41135791e-05 5.53784576e-05 5.77911083e-05]
 [1.54955918e-02 6.27114021e-04 7.03608457e-05 2.94054757e-04]
 [4.78226022e-02 1.64412937e-02 8.53805739e-03 1.30420933e-02]
 [3.92733102e-02 5.08057633e-02 1.87977440e-02 2.43320963e-02]
 [1.43734972e-01 5.95500379e-02 2.70214436e-02 3.35280214e-02]
 [4.27464601e-02 2.30965567e-02 1.46766503e-02 1.50668218e-02]
 [1.38925995e-02 2.09652521e-03 4.57969196e-04 1.26596522e-03]
 [2.61822068e-02 1.01937012e-03 1.39989050e-04 6.53719419e-04]
 [5.87763826e-03 7.27656759e-04 1.41982707e-03 1.83231808e-03]
 [1.44269303e-02 3.87624010e-03 7.15968041e-04 2.43470540e-03]
 [2.65295218e-01 4.80715121e-02 3.18432423e-02 7.03939892e-02]
 [2.48463799e-02 6.62420169e-03 1.45076416e-03 3.91925698e-03]
 [2.00374032e-02 1.19047868e-03 1.83577149e-04 1.20715427e-03]
 [1.84344109e-02 2.14795848e-04 5.52695146e-05 1.05383786e-04]
 [2.28693561e-01 3.04684075e-01 8.69722204e-02 1.20703529e-01]
 [2.77851990e-02 3.75300166e-03 1.20305226e-03 2.08217964e-03]
 [3.47314988e-02 5.06022766e-02 2.96237081e-02 4.48652770e-02]
 [2.77851990e-02 3.75904352e-03 1.79099864e-03 2.97896166e-03]
 [3.31285065e-02 2.29280818e-04 4.75154956e-05 2.23685584e-04]
 [1.49612610e-02 6.24000140e-03 1.71942580e-03 3.90429928e-03]
 [2.56478760e-02 5.74929397e-03 2.07610523e-03 4.69399778e-03]
 [2.93881913e-03 1.03331288e-04 1.18121463e-05 5.09921543e-05]
 [3.49986642e-02 1.03134540e-02 4.05024797e-03 7.84157350e-03]
 [1.73657494e-02 7.74124854e-03 3.04728862e-03 3.32842789e-03]
 [1.30911034e-02 2.86755942e-03 6.85981477e-04 1.73339330e-03]
 [1.46940956e-02 1.11077261e-04 1.44186079e-05 3.33148742e-05]
 [1.65642533e-02 2.56081887e-04 2.76960378e-04 1.24794799e-03]
 [7.48063051e-03 6.95510968e-04 9.46170077e-06 1.52976463e-05]
 [4.14106332e-02 4.43418258e-03 1.26622831e-03 3.98962616e-03]
 [1.95030724e-02 1.49195197e-03 3.13706856e-04 1.16670049e-03]
 [2.80523644e-02 4.33247795e-03 1.66373413e-03 3.11358094e-03]
 [1.49612610e-02 9.11158873e-04 1.49012255e-04 4.31733573e-04]
 [3.20598450e-03 1.68862224e-04 3.48454231e-05 7.07091207e-05]
 [6.67646273e-01 5.54487773e-03 3.77242422e-03 6.69662966e-03]
 [4.54181138e-02 2.13649443e-03 1.08060031e-03 2.36977539e-03]
 [9.35078814e-03 3.34316220e-04 8.59424202e-05 2.89295489e-04]
 [8.73630777e-02 1.46701768e-02 1.33763555e-02 2.03203735e-02]
 [3.58001603e-02 1.76708895e-03 2.59961727e-03 4.83643587e-03]
 [4.32807908e-02 1.89409194e-02 7.21883647e-03 1.41805782e-02]
 [3.04568528e-02 2.35245218e-03 9.40496870e-04 1.85781416e-03]
 [1.20491584e-01 1.35942379e-01 7.94353820e-02 9.20044642e-02]
 [2.93881913e-01 2.84416658e-02 1.21237506e-02 2.89125515e-02]
 [8.06839434e-02 2.80454593e-02 1.12115108e-02 1.95357742e-02]
 [3.55329949e-02 6.14999319e-03 2.34492757e-03 4.25308562e-03]
 [4.08763024e-02 7.92796523e-02 3.62428188e-02 3.66738974e-02]
 [3.09911835e-02 7.41522051e-04 4.23668488e-04 1.51684662e-03]
 [9.99198504e-02 2.19300906e-02 6.14385490e-03 7.71715264e-03]
 [4.03419717e-02 2.43215825e-03 4.74920729e-04 9.89927690e-04]
 [3.39300027e-02 5.12380661e-03 2.16446074e-03 3.34270569e-03]
 [1.92359070e-02 2.41403267e-03 7.29757503e-04 4.31835558e-03]
 [1.14881111e-02 7.05038516e-04 1.10272119e-04 3.93319484e-04]
 [2.67165375e-02 5.69731849e-03 1.74145408e-03 4.09704963e-03]
 [2.80523644e-02 6.03411342e-04 4.29311736e-04 8.11795097e-04]
 [8.28212664e-03 2.18583629e-03 6.79793514e-04 1.55764034e-03]
 [3.09911835e-02 3.65948452e-02 1.79767194e-02 3.18354218e-02]
 [3.07240182e-02 4.72132582e-03 1.27320066e-03 2.23243652e-03]
 [5.26315789e-02 2.14357425e-02 1.32583049e-02 9.86392234e-03]
 [6.14480363e-03 8.00159071e-05 2.52883971e-05 4.82725728e-05]
 [1.46940956e-02 7.78625265e-04 1.48018150e-04 4.52810331e-04]
 [7.74779589e-03 6.36486649e-04 1.17347968e-04 8.84543904e-04]
 [6.67913438e-03 3.53448775e-04 4.52821638e-05 8.77065055e-05]
 [2.16403954e-02 2.56949436e-03 3.70945516e-04 1.78506535e-03]
 [1.79000801e-02 3.21767743e-03 1.22614545e-03 1.97849559e-03]
 [5.74405557e-02 7.35487938e-03 5.33125713e-03 1.15092692e-02]
 [3.84718141e-02 9.89207303e-03 4.91341164e-03 9.06334551e-03]
 [1.28239380e-02 2.64594712e-03 7.94987133e-04 4.54748032e-03]
 [1.68314186e-02 1.99451074e-03 4.98645793e-04 1.09633132e-03]
 [2.45792145e-02 1.72061311e-03 3.51599960e-04 1.07593446e-03]
 [3.87389794e-02 8.95976765e-04 6.72785754e-04 2.58734191e-03]
 [1.62970879e-02 4.42062712e-04 6.95519438e-05 2.42722655e-04]
 [4.94255944e-02 2.01673394e-02 1.13357303e-02 1.32698583e-02]
 [3.01896874e-02 6.74132081e-04 2.58747829e-04 5.53094901e-04]
 [4.86240983e-02 2.28839298e-03 5.20113014e-04 1.54506228e-03]
 [4.51509484e-02 2.01604454e-03 1.02410791e-03 3.37874015e-03]
 [1.76329148e-02 1.56600348e-03 3.48881832e-04 1.43695891e-03]
 [1.04194496e-02 2.91248607e-05 0.00000000e+00 0.00000000e+00]
 [1.09537804e-02 4.29901534e-04 5.95019507e-05 1.52976463e-04]
 [9.35078814e-03 1.35941836e-04 2.17858792e-05 1.08783263e-04]
 [1.41597649e-02 1.93649340e-04 4.41518800e-05 2.45782184e-04]
 [3.58001603e-02 6.20839783e-03 2.09380575e-03 4.75144894e-03]
 [3.63344910e-02 9.49958454e-03 2.34576370e-03 4.73139203e-03]
 [1.49612610e-02 1.19954147e-03 3.60699425e-04 1.58653590e-03]
 [6.67913438e-03 2.78312831e-04 5.59395142e-05 2.07028147e-04]
 [2.56478760e-02 7.83745353e-03 3.16005009e-03 5.18624204e-03]
 [2.13732300e-02 5.06772576e-03 1.03199266e-03 4.48017068e-03]
 [1.39994657e-01 1.36078940e-02 7.45238578e-03 2.03122148e-02]
 [1.25567726e-02 6.24635310e-04 7.43563307e-05 2.17906473e-04]
 [2.24418915e-02 1.16274809e-03 2.56808644e-04 6.00347631e-04]
 [4.75554368e-02 2.23108052e-02 9.37466620e-03 9.92681266e-03]
 [2.31632380e-01 1.80632386e-01 9.12433504e-02 7.50567118e-02]
 [2.93881913e-02 3.09823451e-03 4.35240414e-03 5.05944155e-03]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00]
 [8.28212664e-03 0.00000000e+00 1.45411688e-05 2.68558680e-05]
 [2.16403954e-02 4.82496695e-04 5.13786149e-04 6.54399314e-04]
 [1.92359070e-02 2.32069369e-04 9.19124974e-05 2.86915855e-04]
 [7.21346513e-03 6.21536920e-04 2.34611504e-04 3.62044296e-04]
 [2.53807107e-02 1.19566074e-02 2.29917967e-03 6.60960305e-03]
 [1.38925995e-02 3.61349668e-04 9.07195714e-05 1.64874632e-04]
 [1.36254341e-02 3.45780261e-04 3.97124522e-05 1.03004152e-04]
 [1.95030724e-02 2.12154471e-03 8.41696450e-04 2.38507303e-03]
 [1.92359070e-02 1.35903107e-03 4.12229471e-04 8.15194574e-04]
 [6.67913438e-03 7.60654606e-05 1.14580815e-05 6.62898007e-05]
 [4.27464601e-03 1.78312312e-04 3.57033493e-05 8.43070285e-05]
 [2.37777184e-02 7.33466239e-04 2.38914753e-04 5.99327787e-04]
 [1.49612610e-02 3.89219681e-03 1.08908969e-03 2.51459310e-03]
 [1.49612610e-02 8.57866575e-04 1.01251637e-04 3.31449003e-04]
 [6.97301630e-02 7.37075862e-03 2.10556342e-03 3.20842635e-03]
 [2.13732300e-02 4.13557530e-04 7.79732388e-05 4.45331481e-04]
 [0.00000000e+00 1.07049355e-04 6.23426398e-06 4.14736189e-05]
 [2.29762223e-02 9.21228638e-04 1.72529238e-03 5.83384241e-03]
 [2.64493722e-02 5.60723282e-03 2.52530451e-03 2.76751419e-03]
 [3.33956719e-02 1.39961997e-03 2.14171071e-04 9.28057209e-04]
 [1.54955918e-02 2.83618823e-03 8.03634485e-04 1.31185816e-03]
 [3.41971680e-02 3.95157744e-02 1.35814517e-02 2.00229193e-02]
 [1.01522843e-02 1.34539815e-03 2.23698138e-04 1.13270572e-03]
 [3.05904355e-01 3.64076250e-03 1.67180136e-03 5.32834018e-03]
 [1.49612610e-02 3.27553985e-03 9.91487648e-04 2.24059526e-03]
 [5.34330751e-04 1.04493184e-04 1.07363340e-05 2.99153972e-05]
 [3.63344910e-02 4.90552507e-03 2.03941322e-03 7.36598667e-03]
 [1.28239380e-02 8.60035447e-04 2.63726525e-04 5.56834325e-04]
 [2.51135453e-02 1.71457125e-03 2.59690186e-04 1.02018303e-03]
 [1.92359070e-02 5.02403847e-04 2.11583675e-04 4.84085519e-04]
 [1.38925995e-02 1.47305180e-03 2.86285900e-04 1.07593446e-03]
 [3.50788138e-01 8.02346534e-02 3.31879205e-02 3.93639035e-02]
 [7.21346513e-03 4.66849828e-04 5.96054466e-05 4.46011377e-04]
 [2.61822068e-02 3.48204751e-03 1.35215711e-03 2.99391936e-03]
 [3.49986642e-02 7.54233194e-03 2.75146749e-03 3.80809409e-03]]

In [64]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)
# np.save('./npy/' + 'social_imdb' + '.npy', npy) # for imdb
# np.save('./npy/' + 'social_IG' + '.npy', npy) # for IG

# Movie genre

In [28]:
PATH = '../genresMat.csv'
SAVE_NAME = 'movie_genre'

In [29]:
df = pd.read_csv(PATH)
df

,movie,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,...,History,Horror,Music,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,21bridgesmovie,1,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,47metersdown,0,1,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
2,abeautifuldaymovie,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,abominablemovie,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,adastramovie,0,1,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,wrinklestheclown,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
161,xmenmovies,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
162,yardiefilm,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
163,yesterdaymovie,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
164,zombieland,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [30]:
df = df.iloc[:, 1:]
df

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,History,Horror,Music,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0
161,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
162,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
163,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0
164,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [31]:
npy = df.to_numpy()
print(npy.shape, npy)

(165, 20) [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]

In [ ]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

# User preference

## User following

In [32]:
PATH = '../User/output/UserFollowingsMat.csv'
SAVE_NAME = 'user_followings'

In [33]:
df = pd.read_csv(PATH, header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,156,157,158,159,160,161,162,163,164,165
0,NaN,21bridgesmovie,47metersdown,abeautifuldaymovie,abominablemovie,adastramovie,adogsjourneymovie,aftermathmovie,aftermovie,ahiddenlifefilm,...,underthesilverlake,usmovie,wavesmovie,whatmenwant,wonderparkmovie,wrinklestheclown,xmenmovies,yardiefilm,yesterdaymovie,zombieland
1,2.289300e+04,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2.925001e+06,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,3.002253e+06,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,3.328685e+06,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1578,1.768764e+10,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1579,1.804532e+10,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1580,1.888740e+10,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1581,2.202644e+10,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1582,2.433737e+10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
df = df.loc[1:, 1:]
df

,1,2,3,4,5,6,7,8,9,10,...,156,157,158,159,160,161,162,163,164,165
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1578,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1579,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1580,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1581,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
npy = df.to_numpy().astype(int)
print(npy.shape, npy)

(1582, 165) [[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [ ]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

## User genre

In [3]:
SAVE_NAME = 'user_genre_like'

In [4]:
user_followings = np.load('./npy/user_likes.npy')
movie_genre = np.load('./npy/movie_genre.npy')

In [5]:
user_followings = user_followings.astype(int)
movie_genre = movie_genre.astype(int)

In [6]:
user_genre = user_followings.dot(movie_genre)

In [7]:
print(user_genre.shape)

(1582, 20)

In [8]:
df = pd.DataFrame(user_genre)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,2,2,0,23,4,1,0,38,0,0,20,0,0,0,2,1,0,1,0,0
1,34,49,14,0,82,3,0,13,2,28,0,0,17,0,9,2,0,1,0,0
2,10,17,17,0,38,35,0,41,0,20,0,5,0,4,20,0,2,4,0,0
3,9,15,5,22,26,4,0,80,0,0,0,0,0,3,6,18,0,8,8,0
4,7,6,0,0,16,1,0,1,0,4,0,18,0,8,0,8,0,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1577,18,8,6,0,15,7,0,21,0,1,0,1,0,0,7,7,0,4,0,0
1578,15,20,13,1,7,2,0,6,0,1,0,6,0,4,0,4,0,4,0,0
1579,79,43,0,91,34,23,0,258,0,0,47,3,0,32,6,10,0,8,12,0
1580,6,6,0,8,7,2,0,25,0,0,2,1,0,0,0,2,0,0,1,0
1581,67,53,1,25,40,41,0,90,0,73,5,25,0,0,0,0,0,3,5,0

In [9]:
npy = df.to_numpy()
print(npy.shape, npy)

(1582, 20) [[ 2  2  0 ...  1  0  0]
 [34 49 14 ...  1  0  0]
 [10 17 17 ...  4  0  0]
 ...
 [79 43  0 ...  8 12  0]
 [ 6  6  0 ...  0  1  0]
 [67 53  1 ...  3  5  0]]

In [10]:
# np.save('./npy/' + SAVE_NAME + '.npy', npy)

In [44]:
columns = read_json('../orderedListGenres.json')
print(len(columns), columns)
users = read_json('../orderedListUsers.json')
print(len(users), users[:10])

20 ['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War', 'Western']
1582 [22893, 2925001, 3002253, 3328685, 3920740, 6636654, 8952912, 9099063, 9305486, 10063561]

In [45]:
df.columns = columns
df.index = users
df

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,History,Horror,Music,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
22893,2,1,0,4,2,1,0,9,0,0,2,0,0,0,1,1,0,1,0,0
2925001,4,8,4,0,9,1,0,2,1,4,0,0,1,0,2,1,0,0,0,0
3002253,2,2,2,0,4,2,0,5,0,1,0,2,0,1,1,0,1,1,0,0
3328685,2,5,2,1,7,1,0,6,0,0,0,0,0,0,1,2,0,1,0,0
3920740,3,2,0,0,3,1,0,1,0,2,0,7,0,3,0,2,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17687638563,4,3,2,0,5,1,0,5,0,1,0,1,0,0,2,2,0,1,0,0
18045323488,4,5,2,1,3,2,0,6,0,1,0,3,0,1,0,2,0,1,0,0
18887395150,5,3,0,6,4,5,0,19,0,0,3,1,0,1,1,2,0,1,1,0
22026438960,2,2,0,3,3,1,0,7,0,0,1,1,0,0,0,1,0,0,1,0
24337372261,3,2,0,2,4,4,0,9,0,3,0,3,0,0,0,0,0,1,1,0

In [ ]:
# df.to_csv('../User/output/UserGenreMat.csv')

# Merge all features

In [71]:
text_npy = np.load('./npy/text.npy')
poster_npy = np.load('./npy/poster.npy')
IGimg_npy = np.load('./npy/IGimg.npy')
image_npy = np.load('./npy/image.npy')
video_npy = np.load('./npy/video.npy')
follow_npy = np.load('./npy/follow.npy')
# social_npy = np.load('./npy/social.npy')
# social_npy = np.load('./npy/social_imdb.npy')
social_npy = np.load('./npy/social_IG.npy')

print('Text:', text_npy.shape)
print('Poster:', poster_npy.shape)
print('IGimg:', IGimg_npy.shape)
print('Image:', image_npy.shape)
print('Video:', video_npy.shape)
print('Follow:', follow_npy.shape)
print('Social:', social_npy.shape)

Text: (165, 300)
Poster: (165, 2048)
IGimg: (165, 2048)
Image: (165, 2048)
Video: (165, 8)
Follow: (165, 10)
Social: (165, 4)

In [72]:
# npys = [image_npy, video_npy, follow_npy, social_npy] # for all
# npys = [video_npy, follow_npy, social_npy] # for mask
# npys = [poster_npy, video_npy, social_npy] # for imdb
# npys = [IGimg_npy, follow_npy] # for imdb

In [73]:
tmp = social_npy

for npy in npys:
    tmp = np.hstack([tmp, npy])
    
print(tmp.shape)

(165, 2062)

In [74]:
SAVE_NAME = 'IG'

In [75]:
np.save('./npy/' + SAVE_NAME + '.npy', tmp)