In [1]:
# Basic import
import os
import sys
import json
import shutil
import pandas as pd
import numpy as np
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix

In [2]:
# Helper function
def writeProgress(msg, count, total):
    sys.stdout.write(msg + "{:.2%}\r".format(count/total))
    sys.stdout.flush()
    
def newPath(path):
    if not os.path.isdir(path):
        os.mkdir(path)

def read_json(src_path):
    with open(src_path, 'r') as json_file:
        data = json.load(json_file)
    return data

def write_json(data,dst_path):
    with open(dst_path, 'w') as outfile:
        json.dump(data, outfile)

In [3]:
genres = ['Biography',
         'Animation',
         'Sci-Fi',
         'Fantasy',
         'Romance',
         'Crime',
         'Mystery',
         'Horror',
         'Thriller',
         'Action',
         'Adventure',
         'Comedy',
         'Drama',
         'Others'] # 14 classes
others = ['Western', 'Documentary', 'War', 'History', 'Family', 'Sport', 'Music'] # 7 classes

In [5]:
df = pd.read_csv('./output/result_word2vec_bi.csv')
df

,username,acc,truth,top_n,Biography,Animation,Sci-Fi,Fantasy,Romance,Crime,Mystery,Horror,Thriller,Action,Adventure,Comedy,Drama,Others
0,47metersdown,1.000000,"['Adventure', 'Drama', 'Horror']","['Drama', 'Adventure', 'Horror']",0,0,0,0,0,0,0,1,0,0,1,0,1,0
1,adogsjourneymovie,0.666667,"['Adventure', 'Comedy', 'Drama']","['Drama', 'Others', 'Comedy']",0,0,0,0,0,0,0,0,0,0,0,1,1,1
2,aftermathmovie,0.666667,"['Drama', 'Romance', 'Others']","['Drama', 'Others', 'Thriller']",0,0,0,0,0,0,0,0,1,0,0,0,1,1
3,aftermovie,0.000000,"['Drama', 'Romance']","['Thriller', 'Action']",0,0,0,0,0,0,0,0,1,1,0,0,0,0
4,alitamovie,1.000000,"['Action', 'Adventure', 'Sci-Fi']","['Action', 'Adventure', 'Sci-Fi']",0,0,1,0,0,0,0,0,0,1,1,0,0,0
5,angelhasfallen,0.500000,"['Action', 'Thriller']","['Action', 'Drama']",0,0,0,0,0,0,0,0,0,1,0,0,1,0
6,angrybirdsmovie,1.000000,"['Adventure', 'Animation', 'Comedy']","['Adventure', 'Comedy', 'Animation']",0,1,0,0,0,0,0,0,0,0,1,1,0,0
7,annabellemovie,0.333333,"['Horror', 'Mystery', 'Thriller']","['Sci-Fi', 'Thriller', 'Drama']",0,0,1,0,0,0,0,0,1,0,0,0,1,0
8,annamovie,1.000000,"['Action', 'Thriller']","['Action', 'Thriller']",0,0,0,0,0,0,0,0,1,1,0,0,0,0
9,apollo11movie,1.000000,['Others'],['Others'],0,0,0,0,0,0,0,0,0,0,0,0,0,1
10,arcticmovie,1.000000,"['Adventure', 'Drama']","['Drama', 'Adventure']",0,0,0,0,0,0,0,0,0,0,1,0,1,0
11,artofracingmovie,0.666667,"['Comedy', 'Drama', 'Romance']","['Drama', 'Others', 'Comedy']",0,0,0,0,0,0,0,0,0,0,0,1,1,1
12,avengers,1.000000,"['Action', 'Adventure', 'Sci-Fi']","['Action', 'Sci-Fi', 'Adventure']",0,0,1,0,0,0,0,0,0,1,1,0,0,0
13,beachbummovie,1.000000,['Comedy'],['Comedy'],0,0,0,0,0,0,0,0,0,0,0,1,0,0
14,bernadettefilm,1.000000,"['Comedy', 'Drama', 'Mystery']","['Drama', 'Comedy', 'Mystery']",0,0,0,0,0,0,1,0,0,0,0,1,1,0
15,blindedbythelightmovie,1.000000,"['Comedy', 'Drama', 'Others']","['Drama', 'Comedy', 'Others']",0,0,0,0,0,0,0,0,0,0,0,1,1,1
16,booksmart,0.000000,['Comedy'],['Drama'],0,0,0,0,0,0,0,0,0,0,0,0,1,0
17,breakthroughmovie,0.500000,"['Biography', 'Drama']","['Adventure', 'Drama']",0,0,0,0,0,0,0,0,0,0,1,0,1,0
18,brianbanksmovie,1.000000,"['Biography', 'Drama', 'Others']","['Drama', 'Others', 'Biography']",1,0,0,0,0,0,0,0,0,0,0,0,1,1
19,brightburnmovie,0.500000,"['Horror', 'Sci-Fi']","['Horror', 'Thriller']",0,0,0,0,0,0,0,1,1,0,0,0,0,0
20,brittanyrunsmov,1.000000,"['Comedy', 'Drama']","['Drama', 'Comedy']",0,0,0,0,0,0,0,0,0,0,0,1,1,0
21,captainmarvelofficial,0.333333,"['Action', 'Adventure', 'Sci-Fi']","['Drama', 'Others', 'Sci-Fi']",0,0,1,0,0,0,0,0,0,0,0,0,1,1
22,captivestatemovie,0.333333,"['Drama', 'Sci-Fi', 'Thriller']","['Drama', 'Others', 'Comedy']",0,0,0,0,0,0,0,0,0,0,0,1,1,1
23,childsplaymovie,0.000000,['Horror'],['Adventure'],0,0,0,0,0,0,0,0,0,0,1,0,0,0
24,clarathefilm,0.000000,['Sci-Fi'],['Others'],0,0,0,0,0,0,0,0,0,0,0,0,0,1
25,coldpursuitmovie,0.333333,"['Action', 'Crime', 'Drama']","['Comedy', 'Drama', 'Horror']",0,0,0,0,0,0,0,1,0,0,0,1,1,0
26,detectivepikachumovie,1.000000,"['Action', 'Adventure', 'Comedy']","['Adventure', 'Comedy', 'Action']",0,0,0,0,0,0,0,0,0,1,1,1,0,0
27,disneyaladdin,1.000000,"['Adventure', 'Fantasy', 'Others']","['Adventure', 'Others', 'Fantasy']",0,0,0,1,0,0,0,0,0,0,1,0,0,1
28,doramovie,1.000000,"['Adventure', 'Others']","['Adventure', 'Others']",0,0,0,0,0,0,0,0,0,0,1,0,0,1
29,dumbo,0.666667,"['Adventure', 'Fantasy', 'Others']","['Adventure', 'Others', 'Action']",0,0,0,0,0,0,0,0,0,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,scarystoriesmovie,1.000000,"['Horror', 'Mystery', 'Thriller']","['Horror', 'Thriller', 'Mystery']",0,0,0,0,0,0,1,1,1,0,0,0,0,0
68,secretlifeofpets,1.000000,"['Adventure', 'Animation', 'Comedy']","['Adventure', 'Comedy', 'Animation']",0,1,0,0,0,0,0,0,0,0,1,1,0,0
69,serenityfilm,0.333333,"['Drama', 'Mystery', 'Thriller']","['Drama', 'Others', 'Comedy']",0,0,0,0,0,0,0,0,0,0,0,1,1,1
70,shaftmovie,1.000000,"['Action', 'Comedy', 'Crime']","['Action', 'Comedy', 'Crime']",0,0,0,0,0,1,0,0,0,1,0,1,0,0
71,shazammovie,1.000000,"['Action', 'Adventure', 'Comedy']","['Adventure', 'Comedy', 'Action']",0,0,0,0,0,0,0,0,0,1,1,1,0,0
72,spidermanmovie,1.000000,"['Action', 'Adventure', 'Sci-Fi']","['Sci-Fi', 'Action', 'Adventure']",0,0,1,0,0,0,0,0,0,1,1,0,0,0
73,stubermovie,0.333333,"['Action', 'Comedy', 'Crime']","['Comedy', 'Horror', 'Drama']",0,0,0,0,0,0,0,1,0,0,0,1,1,0
74,taosdfilm,0.333333,"['Comedy', 'Drama', 'Others']","['Drama', 'Thriller', 'Action']",0,0,0,0,0,0,0,0,1,1,0,0,1,0
75,teenspiritmov,1.000000,"['Drama', 'Others']","['Drama', 'Others']",0,0,0,0,0,0,0,0,0,0,0,0,1,1
76,thebestofenemies,0.666667,"['Biography', 'Drama', 'Others']","['Others', 'Drama', 'Adventure']",0,0,0,0,0,0,0,0,0,0,1,0,1,1
77,thedeaddontdie,0.333333,"['Comedy', 'Fantasy', 'Horror']","['Others', 'Fantasy', 'Adventure']",0,0,0,1,0,0,0,0,0,0,1,0,0,1
78,thefarewell,0.000000,"['Comedy', 'Drama']","['Adventure', 'Action']",0,0,0,0,0,0,0,0,0,1,1,0,0,0
79,thehummingbirdprojectfilm,0.000000,['Thriller'],['Drama'],0,0,0,0,0,0,0,0,0,0,0,0,1,0
80,theintrudermovie,0.666667,"['Drama', 'Horror', 'Mystery']","['Drama', 'Others', 'Horror']",0,0,0,0,0,0,0,1,0,0,0,0,1,1
81,thekitchenmovie,1.000000,"['Action', 'Crime', 'Drama']","['Action', 'Drama', 'Crime']",0,0,0,0,0,1,0,0,0,1,0,0,1,0
82,thelegomovie,1.000000,"['Action', 'Adventure', 'Animation']","['Adventure', 'Action', 'Animation']",0,1,0,0,0,0,0,0,0,1,1,0,0,0
83,themustangfilm,0.000000,['Drama'],['Adventure'],0,0,0,0,0,0,0,0,0,0,1,0,0,0
84,theprodigymovie,0.000000,"['Horror', 'Thriller']","['Drama', 'Others']",0,0,0,0,0,0,0,0,0,0,0,0,1,1
85,thesunisalsoastar,0.500000,"['Drama', 'Romance']","['Comedy', 'Romance']",0,0,0,0,1,0,0,0,0,0,0,1,0,0
86,theupsidefilm,1.000000,"['Comedy', 'Drama']","['Drama', 'Comedy']",0,0,0,0,0,0,0,0,0,0,0,1,1,0
87,tolkienmovie,1.000000,"['Biography', 'Drama', 'Others']","['Drama', 'Others', 'Biography']",1,0,0,0,0,0,0,0,0,0,0,0,1,1
88,toystory,1.000000,"['Adventure', 'Animation', 'Comedy']","['Adventure', 'Comedy', 'Animation']",0,1,0,0,0,0,0,0,0,0,1,1,0,0
89,triplefrontier,0.000000,"['Action', 'Adventure', 'Crime']","['Comedy', 'Horror', 'Drama']",0,0,0,0,0,0,0,1,0,0,0,1,1,0
90,uglydolls,1.000000,"['Adventure', 'Animation', 'Comedy']","['Adventure', 'Comedy', 'Animation']",0,1,0,0,0,0,0,0,0,0,1,1,0,0
91,underthesilverlake,0.666667,"['Comedy', 'Crime', 'Drama']","['Drama', 'Others', 'Comedy']",0,0,0,0,0,0,0,0,0,0,0,1,1,1
92,usmovie,0.000000,"['Horror', 'Mystery', 'Thriller']","['Drama', 'Comedy', 'Others']",0,0,0,0,0,0,0,0,0,0,0,1,1,1
93,whatmenwant,0.666667,"['Comedy', 'Fantasy', 'Romance']","['Comedy', 'Fantasy', 'Others']",0,0,0,1,0,0,0,0,0,0,0,1,0,1
94,wonderparkmovie,0.666667,"['Adventure', 'Animation', 'Comedy']","['Adventure', 'Comedy', 'Action']",0,0,0,0,0,0,0,0,0,1,1,1,0,0
95,xmenmovies,1.000000,"['Action', 'Adventure', 'Sci-Fi']","['Action', 'Sci-Fi', 'Adventure']",0,0,1,0,0,0,0,0,0,1,1,0,0,0
96,yesterdaymovie,0.333333,"['Comedy', 'Fantasy', 'Others']","['Comedy', 'Drama', 'Adventure']",0,0,0,0,0,0,0,0,0,0,1,1,1,0

In [6]:
genresDic = read_json('genresDicOthers.json')
len(genresDic)

97

In [7]:
li = []
for i, row in df.iterrows():
    acc = row['username']
    gs = genresDic[acc]
    print(acc, gs)
    glist = []
    newrow = [row['username']]
    for g in genres:
        if g in gs:
            glist.append(1)
        else:
            glist.append(0)
            
    li.append([acc] + glist)

47metersdown ['Adventure', 'Drama', 'Horror']
adogsjourneymovie ['Adventure', 'Comedy', 'Drama']
aftermathmovie ['Drama', 'Romance', 'Others']
aftermovie ['Drama', 'Romance']
alitamovie ['Action', 'Adventure', 'Sci-Fi']
angelhasfallen ['Action', 'Thriller']
angrybirdsmovie ['Adventure', 'Animation', 'Comedy']
annabellemovie ['Horror', 'Mystery', 'Thriller']
annamovie ['Action', 'Thriller']
apollo11movie ['Others']
arcticmovie ['Adventure', 'Drama']
artofracingmovie ['Comedy', 'Drama', 'Romance']
avengers ['Action', 'Adventure', 'Sci-Fi']
beachbummovie ['Comedy']
bernadettefilm ['Comedy', 'Drama', 'Mystery']
blindedbythelightmovie ['Comedy', 'Drama', 'Others']
booksmart ['Comedy']
breakthroughmovie ['Biography', 'Drama']
brianbanksmovie ['Biography', 'Drama', 'Others']
brightburnmovie ['Horror', 'Sci-Fi']
brittanyrunsmov ['Comedy', 'Drama']
captainmarvelofficial ['Action', 'Adventure', 'Sci-Fi']
captivestatemovie ['Drama', 'Sci-Fi', 'Thriller']
childsplaymovie ['Horror']
clarathefilm ['Sci-Fi']
coldpursuitmovie ['Action', 'Crime', 'Drama']
detectivepikachumovie ['Action', 'Adventure', 'Comedy']
disneyaladdin ['Adventure', 'Fantasy', 'Others']
doramovie ['Adventure', 'Others']
dumbo ['Adventure', 'Fantasy', 'Others']
escaperoom ['Action', 'Adventure', 'Horror']
everybodyknowsmovie ['Crime', 'Drama', 'Mystery']
fastandfuriousmovie ['Action', 'Adventure']
fightingwmyfam ['Biography', 'Comedy', 'Drama']
fivefeetapartfilm ['Drama', 'Romance']
glassmovie ['Drama', 'Sci-Fi', 'Thriller']
gloriabellmovie ['Comedy', 'Drama', 'Romance']
godzillamovie ['Action', 'Adventure', 'Fantasy']
goodboysmovie ['Adventure', 'Comedy']
gretafilm ['Drama', 'Mystery', 'Thriller']
happydeathdaymovie ['Comedy', 'Horror', 'Mystery']
hellboymovie ['Action', 'Adventure', 'Fantasy']
hersmellmovie ['Drama', 'Others']
highlifemovie ['Adventure', 'Drama', 'Mystery']
hotelmumbaifilm ['Drama', 'Thriller', 'Others']
httydragon ['Action', 'Adventure', 'Animation']
hustlemovie ['Comedy', 'Crime']
isntitromantic ['Comedy', 'Fantasy', 'Romance']
johnwickmovie ['Action', 'Crime', 'Thriller']
lalloronamovie ['Horror', 'Mystery', 'Thriller']
lastblackmansf ['Drama']
latenightmovie ['Comedy', 'Drama']
lionking ['Adventure', 'Animation', 'Drama']
littlethemovie ['Comedy', 'Fantasy', 'Romance']
littlewoodsfilm ['Crime', 'Drama', 'Others']
longshotmovie ['Comedy', 'Romance']
mamovie2019 ['Horror', 'Thriller']
meninblack ['Action', 'Adventure', 'Comedy']
midsommarmovie ['Drama', 'Horror', 'Mystery']
missbalamovie ['Action', 'Crime', 'Drama']
missinglinkfilm ['Adventure', 'Animation', 'Comedy']
onceinhollywood ['Comedy', 'Drama']
onthebasisofsex ['Biography', 'Drama']
overcomermovie ['Drama', 'Others']
petsematarymovie ['Horror', 'Mystery', 'Thriller']
pomsmovie ['Comedy', 'Drama', 'Others']
rocketmanmovie ['Biography', 'Drama', 'Others']
scarystoriesmovie ['Horror', 'Mystery', 'Thriller']
secretlifeofpets ['Adventure', 'Animation', 'Comedy']
serenityfilm ['Drama', 'Mystery', 'Thriller']
shaftmovie ['Action', 'Comedy', 'Crime']
shazammovie ['Action', 'Adventure', 'Comedy']
spidermanmovie ['Action', 'Adventure', 'Sci-Fi']
stubermovie ['Action', 'Comedy', 'Crime']
taosdfilm ['Comedy', 'Drama', 'Others']
teenspiritmov ['Drama', 'Others']
thebestofenemies ['Biography', 'Drama', 'Others']
thedeaddontdie ['Comedy', 'Fantasy', 'Horror']
thefarewell ['Comedy', 'Drama']
thehummingbirdprojectfilm ['Thriller']
theintrudermovie ['Drama', 'Horror', 'Mystery']
thekitchenmovie ['Action', 'Crime', 'Drama']
thelegomovie ['Action', 'Adventure', 'Animation']
themustangfilm ['Drama']
theprodigymovie ['Horror', 'Thriller']
thesunisalsoastar ['Drama', 'Romance']
theupsidefilm ['Comedy', 'Drama']
tolkienmovie ['Biography', 'Drama', 'Others']
toystory ['Adventure', 'Animation', 'Comedy']
triplefrontier ['Action', 'Adventure', 'Crime']
uglydolls ['Adventure', 'Animation', 'Comedy']
underthesilverlake ['Comedy', 'Crime', 'Drama']
usmovie ['Horror', 'Mystery', 'Thriller']
whatmenwant ['Comedy', 'Fantasy', 'Romance']
wonderparkmovie ['Adventure', 'Animation', 'Comedy']
xmenmovies ['Action', 'Adventure', 'Sci-Fi']
yesterdaymovie ['Comedy', 'Fantasy', 'Others']

In [8]:
true_df = pd.DataFrame(li, columns = ['username'] + genres)
true_df.to_csv('./true_df.csv', index = 0)
true_df

,username,Biography,Animation,Sci-Fi,Fantasy,Romance,Crime,Mystery,Horror,Thriller,Action,Adventure,Comedy,Drama,Others
0,47metersdown,0,0,0,0,0,0,0,1,0,0,1,0,1,0
1,adogsjourneymovie,0,0,0,0,0,0,0,0,0,0,1,1,1,0
2,aftermathmovie,0,0,0,0,1,0,0,0,0,0,0,0,1,1
3,aftermovie,0,0,0,0,1,0,0,0,0,0,0,0,1,0
4,alitamovie,0,0,1,0,0,0,0,0,0,1,1,0,0,0
5,angelhasfallen,0,0,0,0,0,0,0,0,1,1,0,0,0,0
6,angrybirdsmovie,0,1,0,0,0,0,0,0,0,0,1,1,0,0
7,annabellemovie,0,0,0,0,0,0,1,1,1,0,0,0,0,0
8,annamovie,0,0,0,0,0,0,0,0,1,1,0,0,0,0
9,apollo11movie,0,0,0,0,0,0,0,0,0,0,0,0,0,1
10,arcticmovie,0,0,0,0,0,0,0,0,0,0,1,0,1,0
11,artofracingmovie,0,0,0,0,1,0,0,0,0,0,0,1,1,0
12,avengers,0,0,1,0,0,0,0,0,0,1,1,0,0,0
13,beachbummovie,0,0,0,0,0,0,0,0,0,0,0,1,0,0
14,bernadettefilm,0,0,0,0,0,0,1,0,0,0,0,1,1,0
15,blindedbythelightmovie,0,0,0,0,0,0,0,0,0,0,0,1,1,1
16,booksmart,0,0,0,0,0,0,0,0,0,0,0,1,0,0
17,breakthroughmovie,1,0,0,0,0,0,0,0,0,0,0,0,1,0
18,brianbanksmovie,1,0,0,0,0,0,0,0,0,0,0,0,1,1
19,brightburnmovie,0,0,1,0,0,0,0,1,0,0,0,0,0,0
20,brittanyrunsmov,0,0,0,0,0,0,0,0,0,0,0,1,1,0
21,captainmarvelofficial,0,0,1,0,0,0,0,0,0,1,1,0,0,0
22,captivestatemovie,0,0,1,0,0,0,0,0,1,0,0,0,1,0
23,childsplaymovie,0,0,0,0,0,0,0,1,0,0,0,0,0,0
24,clarathefilm,0,0,1,0,0,0,0,0,0,0,0,0,0,0
25,coldpursuitmovie,0,0,0,0,0,1,0,0,0,1,0,0,1,0
26,detectivepikachumovie,0,0,0,0,0,0,0,0,0,1,1,1,0,0
27,disneyaladdin,0,0,0,1,0,0,0,0,0,0,1,0,0,1
28,doramovie,0,0,0,0,0,0,0,0,0,0,1,0,0,1
29,dumbo,0,0,0,1,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,scarystoriesmovie,0,0,0,0,0,0,1,1,1,0,0,0,0,0
68,secretlifeofpets,0,1,0,0,0,0,0,0,0,0,1,1,0,0
69,serenityfilm,0,0,0,0,0,0,1,0,1,0,0,0,1,0
70,shaftmovie,0,0,0,0,0,1,0,0,0,1,0,1,0,0
71,shazammovie,0,0,0,0,0,0,0,0,0,1,1,1,0,0
72,spidermanmovie,0,0,1,0,0,0,0,0,0,1,1,0,0,0
73,stubermovie,0,0,0,0,0,1,0,0,0,1,0,1,0,0
74,taosdfilm,0,0,0,0,0,0,0,0,0,0,0,1,1,1
75,teenspiritmov,0,0,0,0,0,0,0,0,0,0,0,0,1,1
76,thebestofenemies,1,0,0,0,0,0,0,0,0,0,0,0,1,1
77,thedeaddontdie,0,0,0,1,0,0,0,1,0,0,0,1,0,0
78,thefarewell,0,0,0,0,0,0,0,0,0,0,0,1,1,0
79,thehummingbirdprojectfilm,0,0,0,0,0,0,0,0,1,0,0,0,0,0
80,theintrudermovie,0,0,0,0,0,0,1,1,0,0,0,0,1,0
81,thekitchenmovie,0,0,0,0,0,1,0,0,0,1,0,0,1,0
82,thelegomovie,0,1,0,0,0,0,0,0,0,1,1,0,0,0
83,themustangfilm,0,0,0,0,0,0,0,0,0,0,0,0,1,0
84,theprodigymovie,0,0,0,0,0,0,0,1,1,0,0,0,0,0
85,thesunisalsoastar,0,0,0,0,1,0,0,0,0,0,0,0,1,0
86,theupsidefilm,0,0,0,0,0,0,0,0,0,0,0,1,1,0
87,tolkienmovie,1,0,0,0,0,0,0,0,0,0,0,0,1,1
88,toystory,0,1,0,0,0,0,0,0,0,0,1,1,0,0
89,triplefrontier,0,0,0,0,0,1,0,0,0,1,1,0,0,0
90,uglydolls,0,1,0,0,0,0,0,0,0,0,1,1,0,0
91,underthesilverlake,0,0,0,0,0,1,0,0,0,0,0,1,1,0
92,usmovie,0,0,0,0,0,0,1,1,1,0,0,0,0,0
93,whatmenwant,0,0,0,1,1,0,0,0,0,0,0,1,0,0
94,wonderparkmovie,0,1,0,0,0,0,0,0,0,0,1,1,0,0
95,xmenmovies,0,0,1,0,0,0,0,0,0,1,1,0,0,0
96,yesterdaymovie,0,0,0,1,0,0,0,0,0,0,0,1,0,1

In [11]:
y_true = np.array(true_df.iloc[:, 1:])
y_pred = np.array(df.iloc[:, 4:])
print(y_true.shape, y_pred.shape)

(97, 14) (97, 14)

In [12]:
cmatrix = multilabel_confusion_matrix(y_true, y_pred)
cmatrix

array([[[90,  0],
        [ 5,  2]],

       [[88,  0],
        [ 4,  5]],

       [[86,  2],
        [ 3,  6]],

       [[86,  2],
        [ 4,  5]],

       [[87,  0],
        [ 8,  2]],

       [[86,  0],
        [ 8,  3]],

       [[84,  0],
        [11,  2]],

       [[78,  4],
        [ 8,  7]],

       [[73,  8],
        [ 8,  8]],

       [[66,  8],
        [ 5, 18]],

       [[59,  8],
        [ 5, 25]],

       [[52,  9],
        [ 6, 30]],

       [[36, 16],
        [ 5, 40]],

       [[54, 25],
        [ 2, 16]]], dtype=int64)

In [13]:
cmatrix.shape

(14, 2, 2)

In [14]:
cmatrix[:, 0, 0]

array([90, 88, 86, 86, 87, 86, 84, 78, 73, 66, 59, 52, 36, 54],
      dtype=int64)

In [16]:
conmat = pd.DataFrame(data = {
    'genre' : genres,
    'TP' : cmatrix[:, 1, 1],
    'FP' : cmatrix[:, 0, 1],
    'FN' : cmatrix[:, 1, 0],
    'TN' : cmatrix[:, 0, 0]
}, columns=['genre', 'TP', 'FP', 'FN', 'TN'])
conmat

        genre  TP  FP  FN  TN
0   Biography   2   0   5  90
1   Animation   5   0   4  88
2      Sci-Fi   6   2   3  86
3     Fantasy   5   2   4  86
4     Romance   2   0   8  87
5       Crime   3   0   8  86
6     Mystery   2   0  11  84
7      Horror   7   4   8  78
8    Thriller   8   8   8  73
9      Action  18   8   5  66
10  Adventure  25   8   5  59
11     Comedy  30   9   6  52
12      Drama  40  16   5  36
13     Others  16  25   2  54

In [15]:
conmat.to_csv('./confusion_matrix_word2vec.csv', index = 0)